// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSZeYBeL_0mr0Ky0_7cjvbRLObFe9X-Ns',
    appId: '1:774274737207:web:d3361f67bb92a520494bb2',
    messagingSenderId: '774274737207',
    projectId: 'techhaven-f7917',
    authDomain: 'techhaven-f7917.firebaseapp.com',
    storageBucket: 'techhaven-f7917.appspot.com',
    measurementId: 'G-WHN6B73GX9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLTWSX42E3mgpsk3AOtMjLBgcEqxD9tdE',
    appId: '1:774274737207:ios:48e02b066de2c23f494bb2',
    messagingSenderId: '774274737207',
    projectId: 'techhaven-f7917',
    storageBucket: 'techhaven-f7917.appspot.com',
    androidClientId: '774274737207-qe41gcj4o8ank57gemuoei6p4bgc3unm.apps.googleusercontent.com',
    iosClientId: '774274737207-m9qt2mh8ccfhj84ba7gb7j8177acdfe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.techHavenAdmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTWSX42E3mgpsk3AOtMjLBgcEqxD9tdE',
    appId: '1:774274737207:ios:48e02b066de2c23f494bb2',
    messagingSenderId: '774274737207',
    projectId: 'techhaven-f7917',
    storageBucket: 'techhaven-f7917.appspot.com',
    androidClientId: '774274737207-qe41gcj4o8ank57gemuoei6p4bgc3unm.apps.googleusercontent.com',
    iosClientId: '774274737207-m9qt2mh8ccfhj84ba7gb7j8177acdfe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.techHavenAdmin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVro7us-blaxGAP76YwOM5zRcZOVF8s0g',
    appId: '1:774274737207:android:3a88c8944622c844494bb2',
    messagingSenderId: '774274737207',
    projectId: 'techhaven-f7917',
    storageBucket: 'techhaven-f7917.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSZeYBeL_0mr0Ky0_7cjvbRLObFe9X-Ns',
    appId: '1:774274737207:web:173e33df38c72e4c494bb2',
    messagingSenderId: '774274737207',
    projectId: 'techhaven-f7917',
    authDomain: 'techhaven-f7917.firebaseapp.com',
    storageBucket: 'techhaven-f7917.appspot.com',
    measurementId: 'G-D69YNQ60W6',
  );

}